language: python

os: linux
sudo: required
dist: trusty

python:
    - "3.5"

before_install:
    - sudo add-apt-repository -y ppa:beineri/opt-qt56-trusty
    - sudo apt-get -qq update

install:
    - sudo apt-get install -y qt56qbs

before_script:
    - export PATH=/opt/qt56/bin:$PATH

script:
    - py -m unittest discover tests
